#import "@preview/basic-report:0.5.0": *

#show: it => basic-report(
  doc-category: "Final project for the Cloud Computing Technologies course (2025/26 academic year)",
  doc-title: "KakfaDepartures: a Real-Time Cloud-Native departure dashboard for three European airports (Amsterdam-Schiphol, Helsinki-Vantaa & Oslo-Gardermoen",
  author: "Marco Colangelo (67045A)",
  affiliation: "Università degli Studi di Milano, Dipartimento di Informatica \"Giovanni degli Antoni\" ",
  language: "en",
  compact-mode: true,
  heading-color: black,
  it
)
= Introduction 
KafkaDepartures is a cloud-native distributed system that ingest live departure information from three European airports (Amsterdam-Schiphol, Helsinki-Vantaa, Oslo-Gardermoen), normalizes the heterogeneous data formats exposed by their public APIs into a canonical schema, and presents the resulting flight feed through a real-time dashboard with per-airport statistics and a notification stream of departed flights. The project is constructed as a stream-based microservice platform built around Apache Kafka in KRaft mode, where Kafka acts as the single source of truth for all derived state. Heterogeneous external data sources are decoupled from internal consumers through a producer-side adapter pattern, while three non-functional properties - fault tolerance, load balancing and transport layer security - are enforced architecturally rather than at the application level. The resulting system can transparently survive the loss of one broker out of three, scales horizontally on partition-based consumers without code changes, and rejects unauthenticated clients at the TLS layer before any application logic is reached.

= System Architecture
The system follows a producer-broker-consumer pattern centered on a three-broker Kafka cluster running in KRaft combined mode (broker plus controller in the same process), eliminating the need for a separate ZooKeeper ensemble. Three topics back the entire dataflow: 
- flight.telemetry (six partitions, the main event stream of flight upserts and deletions)
- flight.stats (three partitions, periodic aggregated counters per airport)
- flight.alerts (three partitions, structured notifications of departed flights). 
All topics are configured with replication factor three and min.insync.replicas set to two, so that every confirmed write is persisted on at least two brokers before being acknowledged.
External data sources are bridged into the system by three host-side poller processes — one per airport — each acting as an HTTP adapter that translates the airport-specific API format (Schiphol's paginated JSON, Finavia's namespaced XML, Avinor's attribute-based XML) into the canonical schema. Pollers do not speak Kafka directly: they POST to a single internal HTTP gateway, the API-producer service, which serializes events onto the flight.telemetry topic with idempotent semantics. This indirection keeps adapters independent of the messaging layer and concentrates Kafka-specific concerns into one component.
Three internal consumers derive distinct views from the telemetry stream: the stats-aggregator computes rolling daily counters of departed flights and average delay per airport and publishes snapshots on flight.stats every ten seconds; the notifier detects DEPARTED transitions and emits human-readable notifications on flight.alerts; the dashboard is a Flask web application that consumes all three topics in parallel and broadcasts the merged state to connected browsers via Server-Sent Events. The dashboard uses randomly generated consumer group identifiers per instance so that each replica receives the full event stream (broadcast pattern), while the other consumers use static group identifiers to obtain partition-based load distribution.

= System Description
== Components
The API-producer is a FastAPI service exposing a single POST /flight endpoint validated by a Pydantic model that mirrors the canonical schema. Its Kafka producer is configured with acks=all, enable.idempotence=True, retries=2147483647, and gzip compression. Because librdkafka's idempotent producer can enter an irrecoverable fatal state after prolonged broker unavailability, the producer is wrapped in a ResilientProducer class that detects the fatal state and transparently reinstantiates the underlying producer, restoring continuity without container restart. Messages are keyed by airport:flight_code so all events of the same flight land on the same partition and preserve per-flight ordering.

The stats-aggregator is a stateful consumer that on every boot calls a seek_to_start_of_today_utc routine, which queries Kafka for the offset corresponding to 00:00 UTC on each partition and replays the day's telemetry to rebuild in-memory counters. Daily rollover at midnight UTC resets the counters automatically. The delay associated with a DEPARTED event is computed via a cascading fallback: the delay_minutes precomputed by the poller, otherwise the difference between actual_departure or estimated_departure and the schedule, otherwise the system observation time observed_at_utc recorded by the poller at the moment of detection. This last fallback covers cases — frequent for Helsinki — where the upstream API does not publish a departure timestamp.

The notifier consumes flight.telemetry, applies the same delay-resolution cascade, resolves the destination IATA code to a city name through the airportsdata library, and publishes a structured alert on flight.alerts in the form Flight <code> to <city>: departed at <actual> (scheduled: <sched>). An in-memory deduplication set keyed on (airport, flight_code, scheduled_departure) ensures each flight produces exactly one alert per session.

The dashboard runs three Kafka consumers in dedicated background threads (one per topic), maintains in-memory state per airport, and serves an HTML page with three independent boards. Each board displays the next twenty scheduled departures, two aggregated statistics, a scrollable departure feed of today's notifications, and a warning indicator that flashes for five seconds whenever the gate, estimated departure, or status of a flight changes between two snapshots. The destination IATA codes received from pollers are enriched on the server side using airportsdata and a curated airline-code dictionary, so the user-facing labels show full names rather than IATA codes.

== Containerization
All internal services — the three Kafka brokers, the kafka-ui administration interface, the API-producer, the stats-aggregator, the notifier, and the dashboard — run as Docker containers orchestrated by Docker Compose on a single bridge network. The pollers run as host-side Python processes outside the cluster, which is the natural placement for components that perform external HTTP calls and would not benefit from container isolation. Each broker has a dedicated persistent volume for its log directory.

The PKI is bootstrapped by a shell script that generates a self-signed root CA called FlightFlowCA, a server keystore and truststore in PKCS12 format for each broker, and a client certificate-key pair in PEM format for the consumers and producers running inside the cluster. All brokers listen on three SSL listeners — one for inter-controller traffic, one for inter-broker replication, and one for client connections — with ssl.client.auth=required enforcing mutual TLS. The keystore password is provided to the brokers through an environment variable sourced from a .env file that is excluded from version control. Healthchecks on each container ensure that dependent services start only when their dependencies are operationally ready.

= Non-functional properties
== Fault Tolerance
The system tolerates the loss of one broker out of three with full operational continuity. After stopping any broker, the partition leadership is reassigned within milliseconds by the KRaft quorum, the in-sync replica set drops from three to two, and producers continue to write because min.insync.replicas=2 is still satisfied. The dashboard, the API-producer, and all the consumers reconnect transparently to surviving brokers. When the affected broker is restarted, it rejoins the cluster and resynchronizes from the current leaders without manual intervention.

When two brokers are down simultaneously the system enters a controlled degraded state: writes are held in the producer's local queue because the in-sync replica count drops below the configured threshold. This is by design — the alternative would mean accepting writes with reduced durability guarantees. Upon recovery, the queued messages are delivered automatically thanks to the producer's idempotent semantics and infinite retry policy. A dedicated experiment confirmed that a flight with a unique identifier injected during the outage was successfully persisted to the topic only after broker recovery, with no duplication.

Consumer-side fault tolerance is verified by killing the stats-aggregator while the system is running and observing its recovery. On restart, the consumer rebuilds the day's counters from the seek-to-midnight-UTC mechanism, producing values consistent with the pre-crash state plus any departures that occurred during the outage. The dashboard recovers from disconnections through the native EventSource auto-reconnect, refetching the snapshot from the REST endpoint and resuming the SSE stream.
== Load Balancing
Horizontal scaling of the consumer side is delivered natively by Kafka. Scaling the storage-class consumer pattern (demonstrated through the stats-aggregator and the notifier) from one to three replicas causes Kafka to redistribute the six partitions of flight.telemetry evenly, two per replica, with each replica processing only its assigned share of events. The mechanism requires no additional code: it follows from using a static consumer group identifier and from the partition-key choice (airport:flight_code), which ensures all events of the same flight reach the same replica. This is the appropriate scaling strategy for components that perform partition-local work.
The dashboard adopts the opposite pattern. Each dashboard instance generates a unique random consumer group identifier at boot, so it forms its own consumer group and receives the full event stream. Multiple dashboard tabs or replicas all see the same up-to-date data, which is the correct semantic for a UI-facing component.
The stats-aggregator is intentionally not scaled horizontally: aggregating a global counter across partitions would require a downstream reduce stage that is not justified for the project's data volume. This is a documented design decision rather than a limitation.
== Security
All transport between cluster components is secured by mutual TLS. Every broker presents a certificate signed by the internal FlightFlowCA, and every client (the API-producer, the consumers, kafka-ui) presents a client certificate signed by the same CA. Validation experiments using a rogue producer demonstrated that three categories of attacks are rejected at the transport layer before any application code is reached: a plain TCP connection is closed by the broker upon receiving a non-TLS handshake; a TLS connection without a client certificate is rejected during the handshake because client authentication is required; a TLS connection presenting a self-signed certificate not chained to FlightFlowCA fails certificate verification. In all three cases, no payload reaches the topic and no document with the rogue identifier appears anywhere in the system.

Packet capture on the broker's internal listener confirmed that the wire payload is uniformly encrypted: no application string — flight codes, IATA identifiers, JSON structure — is observable in the packet contents. The keystore holding the broker's private key is in PKCS12 format and is encrypted with a password sourced from the environment, never stored in version control. The same security model applies to kafka-ui, which uses the same client certificate mechanism: there is no administrative back door.

= The running application
